// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.InfraStructure.Data.Context;

namespace Projeto.InfraStructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto.Domain.Entities.FuncaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Funcao");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.FuncionarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAdmissao");

                    b.Property<int>("IdFuncao");

                    b.Property<int>("IdSetor");

                    b.Property<string>("Nome");

                    b.Property<decimal>("Salario");

                    b.HasKey("Id");

                    b.HasIndex("IdFuncao");

                    b.HasIndex("IdSetor");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.SetorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.FuncionarioEntity", b =>
                {
                    b.HasOne("Projeto.Domain.Entities.FuncaoEntity", "Funcao")
                        .WithMany("Funcionarios")
                        .HasForeignKey("IdFuncao")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Projeto.Domain.Entities.SetorEntity", "Setor")
                        .WithMany("Funcionarios")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
